version: '3'

services:
  sleek-airflow:
    image: sleek-airflow:latest
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./airflow:/opt/airflow
      - ./root:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
